export default {                                                                                                                                                                                                 
    async fetch(request, env) {                                                                                                                                                                                    
      const url = new URL(request.url);                                                                                                                                                                            
      const corsHeaders = {                                                                                                                                                                                        
        'Access-Control-Allow-Origin': '*',                                                                                                                                                                        
        'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',                                                                                                                                                      
        'Access-Control-Allow-Headers': 'Content-Type',                                                                                                                                                            
      };                                                                                                                                                                                                           
                                                                                                                                                                                                                   
      // Handle CORS preflight                                                                                                                                                                                     
      if (request.method === 'OPTIONS') {
        return new Response(null, { headers: corsHeaders });                                                                                                                                                       
      }                                                                                                                                                                                                            
                                                                                                                                                                                                                   
      // GET / — health check                                                                                                                                                                                      
      if (url.pathname === '/') {
        return new Response('Research Translator Proxy is active.', { headers: corsHeaders });                                                                                                                     
      }                                                                                                                                                                                                            
                                                                                                                                                                                                                   
      // GET /fetch?url=... — proxy external URLs (KU Pure)                                                                                                                                                        
      if (url.pathname === '/fetch') {                                                                                                                                                                             
        const targetUrl = url.searchParams.get('url');                                                                                                                                                             
        if (!targetUrl) {                                                                                                                                                                                          
          return new Response('Missing ?url= parameter', { status: 400, headers: corsHeaders });                                                                                                                   
        }                                                                                                                                                                                                          
        try {                                                                                                                                                                                                      
          const resp = await fetch(targetUrl, {                                                                                                                                                                    
            headers: { 'User-Agent': 'Research-Translator-Proxy' },                                                                                                                                                
          });                                                                                                                                                                                                      
          const body = await resp.text();                                                                                                                                                                          
          return new Response(body, {                                                                                                                                                                              
            status: resp.status,                                                                                                                                                                                   
            headers: { ...corsHeaders, 'Content-Type': resp.headers.get('Content-Type') || 'text/html' },                                                                                                          
          });                                                                                                                                                                                                      
        } catch (err) {                                                                                                                                                                                            
          return new Response(`Proxy error: ${err.message}`, { status: 502, headers: corsHeaders });                                                                                                               
        }                                                                                                                                                                                                          
      }                                                                                                                                                                                                            
                                                                                                                                                                                                                   
      // POST /api/anthropic — forward to Anthropic API                                                                                                                                                            
      if (url.pathname === '/api/anthropic') {                                                                                                                                                                     
        const apiKey = env.ANTHROPIC_API_KEY;                                                                                                                                                                      
        if (!apiKey) {                                                                                                                                                                                             
          return new Response('ANTHROPIC_API_KEY not configured', { status: 500, headers: corsHeaders });                                                                                                          
        }                                                                                                                                                                                                          
        try {                                                                                                                                                                                                      
          const body = await request.json();                                                                                                                                                                       
          const resp = await fetch('https://api.anthropic.com/v1/messages', {                                                                                                                                      
            method: 'POST',                                                                                                                                                                                        
            headers: {                                                                                                                                                                                             
              'Content-Type': 'application/json',                                                                                                                                                                  
              'x-api-key': apiKey,                                                                                                                                                                                 
              'anthropic-version': '2023-06-01',                                                                                                                                                                   
            },                                                                                                                                                                                                     
            body: JSON.stringify(body),                                                                                                                                                                            
          });                                                                                                                                                                                                      
          const data = await resp.text();                                                                                                                                                                          
          return new Response(data, {                                                                                                                                                                              
            status: resp.status,                                                                                                                                                                                   
            headers: { ...corsHeaders, 'Content-Type': 'application/json' },                                                                                                                                       
          });                                                                                                                                                                                                      
        } catch (err) {                                                                                                                                                                                            
          return new Response(`Anthropic proxy error: ${err.message}`, { status: 502, headers: corsHeaders });                                                                                                     
        }                                                                                                                                                                                                          
      }                                                                                                                                                                                                            
                                                                                                                                                                                                                   
      return new Response('Not found', { status: 404, headers: corsHeaders });                                                                                                                                     
    },                                                                                                                                                                                                             
  };
